package com.easyupload.photos.s3;

import org.springframework.beans.factory.annotation.Autowired;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.document.DynamoDB;
import com.amazonaws.services.dynamodbv2.document.Item;
import com.amazonaws.services.dynamodbv2.document.Table;

@DynamoDBTable(tableName="PhotoComments")
public class PhotoCommentsDAO {
	private String commentId;
	@Autowired
	private AmazonDynamoDB dynamoDBClient;
	
	@DynamoDBHashKey(attributeName = "commentId")
    @DynamoDBAutoGeneratedKey
    public String getcommentId() { return commentId; }
	public void setcommentId(String commentId) { this.commentId = commentId; } 
	
	public String createItems(Number eventId,String comment) {
		System.out.println("getcommentId():"+getcommentId());
		String tableName="PhotoComments";
	    DynamoDB dynamoDB = new DynamoDB(dynamoDBClient);
		Table table = dynamoDB.getTable(tableName);
	     try {

	         Item item = new Item()
	        		 			.withPrimaryKey("commentId", getcommentId())
	        		 			.withNumber("eventId", eventId)
	        		 			.withString("Comment",comment);
	         table.putItem(item);
	         
	     }
	     catch (Exception e) {
	         System.err.println("Create items failed.");
	         System.err.println(e.getMessage());
	         return e.getMessage();
	     }
	     return "comment added";
	}
}
